// pico8_globals.h
//
// Shared engine state across the engine TU and the retro-go backend TU.
//
// Background:
//   PicoPico's source files (data.h, pico8api.h, sfx.c) declare engine state
//   with `static`, meaning each translation unit gets its own private copy.
//   For the retro-go port we need the backend (separate TU) to see the same
//   memory the engine TU is mutating. Hence this header declares the shared
//   globals as `extern`; the actual definitions live in pico8_globals.c and
//   are linked into the firmware once.
//
// Shared at this point (the 4 integration-pass TODOs require them):
//   - Input:   buttons[7], buttons_frame[7]
//   - Display: frontbuffer, palette[16], pal_map[16], original_palette[16]
//   - Audio:   channels[4] (and the fill_buffer driver symbol declared in sfx.h)
//   - PICO-8 boot time (read by _lua_time): bootup_time
//
// NOT shared (engine-TU only): ram, drawstate, cartdata, spritesheet,
// fontsheet, map_data, sfx[], audiobuf[], orig_pal_map (kept private for now
// - savestate / debug work in a later pass).

#pragma once

#include "data.h"        // for color_t / palidx_t / SCREEN_WIDTH / SCREEN_HEIGHT
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// --- Input -----------------------------------------------------------------
extern uint8_t buttons[7];
extern uint8_t buttons_frame[7];

// --- Display ----------------------------------------------------------------
// Runtime palette (lua can remap via _lua_pal). PICO-8 indexes into these via
// frontbuffer nibbles after a pal_map remap step.
extern color_t   palette[16];
extern uint8_t   pal_map[16];

// Nibble-packed engine framebuffer: 2 pixels per byte (low nibble = even x).
// PICO-8 canonical resolution 128x128 -> 64*128 bytes = 8192 bytes.
extern palidx_t *frontbuffer;

// Canonical (immutable) PICO-8 RGB565 palette used by engine internals and
// by the retro-go backend's `screen->palette` initialisation.
extern const color_t original_palette[16];

// --- Boot time -------------------------------------------------------------
extern uint32_t bootup_time;

// --- Builtin byte arrays (engine-side stubs; populated later) ---------------
// These back the engine_init() memcpy of font.lua / hud.p8 spritesheet
// data, and init_lua()'s load of the PICO-8 stdlib prelude. They are
// declared here so they link from the engine TU; the actual byte contents
// should be generated by a future CMake step from `artifacts/font.lua`,
// `artifacts/hud.p8`, and `stdlib/stdlib.lua` (which is currently a TODO
// for the integration pass — we ship empty stubs so the build links).
extern const uint8_t stdlib_stdlib_lua[];
extern const uint32_t stdlib_stdlib_lua_len;
extern const uint8_t artifacts_font_lua[];
extern const uint32_t artifacts_font_lua_len;
extern const uint8_t artifacts_hud_p8[];
extern const uint32_t artifacts_hud_p8_len;

#ifdef __cplusplus
}
#endif
